jwt:
  secret: babadjanovmamatsalayatabekovich000111999222888333777444555666
  expiration: 864000

server:
  port: 8080

spring:
  main:
    allow-circular-references: false
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: graphql-service
          uri: http://localhost:8081
          predicates:
            - Path=/graphql/**
          filters:
            - RewritePath=/graphql/(?<segment>.*), '/${segment}'
        - id: register-service
          uri: http://localhost:8082
          predicates:
            - Path=/v1/api/**

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG